server:
  port: 12345
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false
---

spring:
  profiles: peer
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
     defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka

