server:
  port: 12345
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: false
    register-with-eureka: false
   # eureka-service-url-poll-interval-seconds: 30
    service-url:
      defaultZone: http://localhost/${server.port}/eureka
  server:
    enable-self-preservation: false